### ISSUE TITLE
Updates have broken IsoElasticDevito forward modelling 

### ISSUE THREAD

**Issue by TomRobins** [trustimaging/stride#26]
No received signal is seen when running elastic forward models with the IsoElasticDevito pde. When looking at the received data acquired over a ring array of receiving elements, only the trace at the src element is non-zero and this only contains the source signal assigned to that element.

The elastic modelling does work on Stride as early as 25/01/2022 (commit 1e8bf26b601bbf289328551cfc4d79fe3731f262). However, more recent updates seem to have broken this functionality.

**Comment by Renjh-rab** [comment]
Has this problem been resolved now? I also encountered this issue where I was unable to obtain data while running the elastic model. thanks

**Comment by oscarbates** [comment]
Hi, I'm afraid this is still an issue and I won't have time to repair it for the forseeable future. If you wanted to tackle it, the code is in stride->physics->isoelastic
